server:
  port: 80

eureka:
  instance:
    instance-id: consume-instance-80
  client:
    service-url         :
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: true
    fetch-registry      : true

spring:
  devtools   :
    livereload:
      port: 8889
  application:
    name: SpringCloud-Consumer